name: Build and Deploy to Azure Container App

on:
  push:
    branches:
      - 'main'

jobs:
  build-and-deploy:
    name: 'Build and Deploy to ACR and Container App'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 🔹 Login to Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
           client-id: ${{ secrets.AZURE_CLIENT_ID }}
           tenant-id: ${{ secrets.AZURE_TENANT_ID }}
           subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Docker Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_URL }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Docker Image to ACR
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.AZURE_URL }}/my-container-app:${{ github.sha }}
          file: ./Dockerfile

      # 🔹 Deploy the container app
      - name: Deploy Container App
        uses: azure/container-apps-deploy-action@v0
        with:
          appSourcePath: ${{ github.workspace }}
          acrName: mycontainerregistry0
          acrUsername: ${{ secrets.ACR_USERNAME }}
          acrPassword: ${{ secrets.ACR_PASSWORD }}
          containerAppName: my-container-app
          containerAppEnvironment: ${{ secrets.CONTAINER_APP_ENVIRONMENT }}
          resourceGroup: ${{ secrets.RESOURCE_GROUP }}
          imageToBuild: ${{ secrets.AZURE_URL }}/my-container-app:${{ github.sha }}
          dockerfilePath: ./Dockerfile
