name: Deploy to Azure Container Apps

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}

    - name: Deploy to Azure Container Apps
      uses: azure/container-apps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_CONTAINER_APP_NAME }}
        resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
        image: ${{ secrets.AZURE_CONTAINER_IMAGE }}
        environment-id: /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/${{ secrets.AZURE_RESOURCE_GROUP }}/providers/Microsoft.App/managedEnvironments/myContainerAppEnv
